CREATE DATABASE TinaService


CREATE TABLE public."GenerateNumber"
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    signature character varying COLLATE pg_catalog."default" NOT NULL,
    key1 character varying COLLATE pg_catalog."default" NOT NULL,
    key2 character varying COLLATE pg_catalog."default" NOT NULL,
    key3 character varying COLLATE pg_catalog."default" NOT NULL,
    date date NOT NULL,
    create_at time without time zone NOT NULL DEFAULT now(),
    CONSTRAINT "GenerateNumber_pkey" PRIMARY KEY (id)
)

TABLESPACE pg_default;

ALTER TABLE public."GenerateNumber"
    OWNER to postgres;